language: node_js
sudo: required
node_js:
  - "6.9"
env:
  - CXX=g++-4.8
before_install:
  - chmod +x /*
before_script:
  - chmod +x /*
install:
  - npm install
  - chmod +x node_modules/.bin/*
notifications:
  slack: niobi:WW01STIxrmCAQfbm9FZzW30v
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8