language: node_js
sudo: required
node_js:
  - "6.9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install babel-cli
  - chmod +x node_modules/.bin/*
  - npm install
notifications:
  slack: niobi:WW01STIxrmCAQfbm9FZzW30v