language: node_js
sudo: required
before_script: chmod +x node_modules/.bin/*
node_js:
  - "6.9"
env:
  - CXX=g++-4.8
notifications:
  slack: niobi:WW01STIxrmCAQfbm9FZzW30v
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8